name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  backend-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.4'
          extensions: dom, curl, libxml, mbstring, zip, pcntl, pdo, sqlite, pdo_sqlite, bcmath, soap, intl, readline, ldap, msgpack, igbinary, redis, swoole, pcov
          coverage: pcov

      - name: Install Composer Dependencies
        run: composer install -q --no-ansi --no-interaction --no-scripts --no-progress --prefer-dist
        working-directory: ./backend

      - name: Copy .env
        run: php -r "file_exists('.env') || copy('.env.example', '.env');"
        working-directory: ./backend

      - name: Generate key
        run: php artisan key:generate
        working-directory: ./backend

      - name: Run Pest Tests
        run: vendor/bin/pest
        working-directory: ./backend

      - name: Run PHPStan
        run: vendor/bin/phpstan analyse
        working-directory: ./backend

  frontend-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '22'
          cache: 'npm'
          cache-dependency-path: './frontend/package-lock.json'

      - name: Install npm dependencies
        run: npm ci
        working-directory: ./frontend

      - name: Run ESLint
        run: npm run lint
        working-directory: ./frontend